#!/bin/sh
#
# This script set an environment to forward a graphical output of an X
# application in a Docker container on a remote server connected via SSH.
# The idea is from the following link:
# https://stackoverflow.com/a/48235281/1554704
#
# To make this script works, you need to edit /etc/ssh/sshd_config and set:
#
# X11UseLocalhost no
#

XAUTH=/tmp/.docker.xauth
xauth nlist $DISPLAY | sed -e 's/^..../ffff/' | sudo xauth -f $XAUTH nmerge -
sudo chmod 777 $XAUTH
X11PORT=`echo $DISPLAY | sed 's/^[^:]*:\([^\.]\+\).*/\1/'`
TCPPORT=`expr 6000 + $X11PORT`
sudo ufw allow from 172.17.0.0/16 to any port $TCPPORT proto tcp
DISPLAY=`echo $DISPLAY | sed 's/^[^:]*\(.*\)/172.17.0.1\1/'`
sudo docker run --name kwchun-tf --gpus all --ipc=host --shm-size=1g \
   --ulimit memlock=-1 --ulimit stack=67108864 --rm -it -p 9000:8888 \
   -p 9001:6006 -e OPENBLAS_CORETYPE=skylike \
   -e HOST_PERMS="$(id -u):$(id -g)" -v /home/kwchun:/home/kwchun \
   -e DISPLAY=$DISPLAY -v $XAUTH:$XAUTH -e XAUTHORITY=$XAUTH \
   ruddyscent/tensorflow:21.03-tf1-py3 \
   jupyter lab --notebook-dir=/home/kwchun --NotebookApp.token='' --NotebookApp.password='' \
