#!/bin/sh
#
# This script set an environment to forward a graphical output of an X 
# application in a Docker container on a remote server connected via SSH. 
# The idea is from the following link:
# https://stackoverflow.com/a/48235281/1554704
#
# To make this script works, you need to edit /etc/ssh/sshd_config and set:
#
# X11UseLocalhost no
#

XAUTH=/tmp/.docker.xauth
xauth nlist $DISPLAY | sed -e 's/^..../ffff/' | sudo xauth -f $XAUTH nmerge -
sudo chmod 777 $XAUTH
X11PORT=`echo $DISPLAY | sed 's/^[^:]*:\([^\.]\+\).*/\1/'`
TCPPORT=`expr 6000 + $X11PORT`
sudo ufw allow from 172.17.0.0/16 to any port $TCPPORT proto tcp 
DISPLAY=`echo $DISPLAY | sed 's/^[^:]*\(.*\)/172.17.0.1\1/'`
sudo docker run --rm -it -e DISPLAY=$DISPLAY -v $XAUTH:$XAUTH \
   -e XAUTHORITY=$XAUTH ruddyscent/pytorch:21.03-py3
